server:
  port: 8090

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  profiles:
    active: local

ed-app:
  emotion-recognition:
    video-path: ${video-path}
    model-path: ${model-path}
    log-emotion: ${log-emotion}

video-path: -1

model-path: cnnModel.bin

log-emotion: false
