server:
  port: 8090

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  profiles:
    active: local

ed-app:
  emotion-recognition:
    video-path: ${video-path}

video-path: -1
